### ISSUE TITLE
说说我的入坑记录

### ISSUE THREAD

**Issue by lifetin** [Jiiiiiin/vue-viewplus#1]
1,必须安装babel/plugin-proposal-function-bind
	npm install --save-dev @babel/plugin-proposal-function-bind
2,这个文件不存在import jsComponents from './util/js-commponent'
	要删掉
3  Error: Cannot find module 'lodash/values'
	要安装lodash
	cnpm i --save lodash
4 	npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
	接着安装	cnpm install ajv@^6.0.0
这些安装好后,接着还是报错. 如下图. 都照官方文档安装了, 还不行,也找不出来原因
说说针对这个模块的看法吧. 他这个依赖较多,可能对小项目不合适,因为一旦用起来,可能编译出来的JS,再配合自己项目中一些模块,最后生成的JS可能比较大.
然后文档也不是特别详情,特别是安装及环境和所依赖的模块来讲.

看了下这个package,dev里面安装了不少模块. 我不知道这些作者会不会在开发时,或编译时感觉会比较慢?
然后是为了自己的一些语法习惯吧. 写的代码如this::xxx() 这是用了一个第三方的模块, 感觉要想做出来好的产品,需要尽可能的少依赖,因为继然发布出来了,肯定是要大家都使用, 但是一看到包这么大,可能很多人会望而却步的. 

![22](https://user-images.githubusercontent.com/10474968/50483637-9fa67780-0a27-11e9-9e51-ba619a82ddf7.png)
![33](https://user-images.githubusercontent.com/10474968/50483639-a03f0e00-0a27-11e9-9bec-b69fbb7fea4f.png)
![44](https://user-images.githubusercontent.com/10474968/50483640-a03f0e00-0a27-11e9-8bee-11f9f4bf1fbe.png)

**Comment by lifetin** [comment]
可能我这小项目,装不了这么多插件和模块吧. 也不想依赖太多的东西,想尽量减少体积极, 所以还是放弃了. 
我是冲着这个http模块来的.

**Comment by Jiiiiiin** [comment]
哈哈哈 冲着你这份吃螃蟹的精神怎么也要好好答复一下了，我现在在地铁上，先简单说一下：
1.你的提议“做插件最好不要以为异己好误添加过多依赖”，这一点我是赞同的 (*°∀°)=3
2.我看你的吃螃蟹过程，应该已经过了9981难，只差针对“babel/plugin-proposal-function-bind”这个的babel配置，没有配，待会到公司我会更新文档予以说明。
另外我解释一下为什么要用它，以为我希望确保插件暴露的API的执行对象，及上下文this是插件本身，这个插件的作业就是用来指定执行函数的this，只是尚未被es纳入规范。
另外我也推荐大家使用他，毕竟熟悉之后，带来的项目开发帮助比编译时候带来的些许时间耗损要划算的多。
3.lodash或者说整个插件为什么要在webpack做单独配置，就是为了减少编译损耗，你可以搜索一下“后编译”，这个词我也是从cube-ui哪里听来的，但是我这样做之前并不知道还有这一种说法，这个作业就是，插件将以源码的方式引入项目，所以你在安装插件的时候，安装完毕其实npm 会提示你，这个插件依赖了些什么插件，什么插件是自带依赖，什么是需要你手动安装的，lodash就是其中之一，为什么我不直接依赖lodash，到站了 待会接着写

**Comment by Jiiiiiin** [comment]
为什么我不直接依赖lodash，是因为我怕大家以为整个插件要依赖这么一个庞然大物，那么我们其实就需要利用后编译整个契机，去做一些事情，即解决lodash过大，就需要找一个按需引入lodash的方式，即使用者手动安装`babel-plugin-lodash`，那在安装`babel/plugin-proposal-function-bind`和`babel-plugin-lodash`的时候，对应插件的文档肯定需要你修改你的bable配置，如：
```js
{
  //...
  ],
  "plugins": [
   //....
    "transform-function-bind",
    "lodash"
  ],
  "env": {
   //...
    }
  }
}
```
其实为什么我没有写清楚，大概是因为这两个插件我都觉得是开发必备，或者说跟着npm提示应该能摸索下来的。
而从这点看来，后编译给我们带来的好处就是：
1. 可以利用webpack tree shaking，让插件和对应依赖在最终输出生产的时候，能**按需加载**
2. 针对你只希望使用http模块的需求，其实一个不太优雅的方法就是，你安装完viewplus之后，可以直接手动修改node_modules对应插件src中的代码，那么你可以直接把：
viewplus src/mian.js
```js
}(opts)
  MixinPlugin.mixin(Vue, defPlugin, '初始化模块')
  utilCacheInstall(Vue, opts)
  cacheUserInfoInstall(Vue, opts)
  jsBridgeContextInstall(Vue, opts)
  loginStateCheckInstall(Vue, opts)
  utilHttpInstall(Vue, opts)
  paramsStackInstall(Vue, opts)
  Vue.use(EventBus, opts)
  const plugin = Vue.prototype[PLUGIN_VM_PREFIX_VIEWPLUS]
  Object.defineProperty(plugin, 'version', {
    value: process.env.VERSION
  })
```
对应不需要的模块的安装方法给注释掉。

**Comment by Jiiiiiin** [comment]
当然，我再写插件的第一时间，就考虑能不能让用户动态的配置需要使用的模块，一开始的版本，我使用的是动态引入`import()`，这也是为什么插件最终打包使用的是webpack的原因，而之后我觉得动态引入太受限制，因为插件模块之间或多或少会有关联，那么模块安装的先后或者说会给大家带来更大的困惑，那么我就在想，能不能让项目直接引入源码，这样就能解决按需引入的问题，因为插件目前只有少部分公司使用，所以后来在改动的时候，我就把模块的**是否按照**参数配置取消了，从你这个需求我觉得还是有必要加回去，那么就不用大家去修改源码，只需要在对应模块配置是否需要，当然我认为默认加载的所有模块都是必须的，针对普通企业级项目而言，当然因为大家可能并不需要这么多，那么周末我会改一下，加上这个配置。

**Comment by Jiiiiiin** [comment]
从viewplus支持webpack3和webpack4（不同的后编译配置）就可以看出来，我们其实是经过了vue-cli2再到cli3的，也就是说这个后编译的方案，其实我们做出来的时候，我们并没有看到有其他插件这么做的，直到我偶然看到cube-ui以这个名词这样解释，当然他们做的是组件库，我们做的是业务插件库。

最后说一点，小哥 @lifetin 小哥能看上http模块，其实我觉得很不错呀，呵呵，因为这个插件其实创建之初，就只有这么一个模块，当时我们还在使用requirejs，就为了解决类似下面这种冗长代码：
```js
onCheckToken:function(params){
		var me = this;
		var url = globalDict.get('commonUrl') + 'CheckToken.do?' + globalDict.get('commonUrlParts');

		MobileBank.mainContainer.mask({
			xtype: 'loadmask',
			message: globalMsg.get('Loading')
		});
		try{
			var request = Ext.Ajax.request({
				url: url,
				method: 'POST',
				disableCaching: true,
				headers: globalSession.header,
				params:params,
				success: function(response){
					try{
						var res = JSON.parse(response.responseText);
						if (res.ReturnCode == globalDict.get('SuccessCode')) {
							if(res.CheckToken=='Y'){
								me.getLoginView().query('textfield[name="LoginToken"]')[0].setHidden(false);
								me.getLoginView().onTapImageToken();
							}else{
								me.getLoginView().query('textfield[name="LoginToken"]')[0].setValue('');
								me.getLoginView().query('textfield[name="LoginToken"]')[0].setHidden(true);
							}
						}
						else {
							var msg = globalTools.decodeBase64(res.ReturnMessage);
							Ext.Msg.alert(globalMsg.get('Error'), msg);
						}
					}catch(e){
						Ext.Msg.alert(globalMsg.get('Error'), e);
					}
				},
				
				failure: function(response){
					Ext.Msg.alert(globalMsg.get('Failure'), globalMsg.get('CommunicationError'));
				},
				
				callback: function(response){
					MobileBank.mainContainer.unmask();
					var loginuserid = me.getLoginView().query('textfield[name="LoginUserId"]')[0];
					loginuserid.setReadOnly(false);
				}
			});
			
			return request;
		}catch(err){
			MobileBank.mainContainer.unmask();
			Ext.Msg.alert(globalMsg.get('Error'), err);
			var loginuserid = me.getLoginView().query('textfield[name="LoginUserId"]')[0];
			loginuserid.setReadOnly(false);
		}
	}
```
一个请求，除了真正的业务代码，其他模板代码其实占据了70%，而这种编码方式是不可想象的。所以一开始我们就有了自己的一个内部函数模块http.js就是解决这个痛点。

既然你都填坑填到这里，并且看出了这个模块的好处，我觉得你可以再试试。
另外我想说一个就是，使用任何插件，看文档肯定是必要的，但是示例工程也可以看看，你就知道，那么js-component模块，其实我好想已经说过了，它其实是一个应用自定义的viewplus模块，需要自己编写，[手动mixin](http://jiiiiiin.cn/vue-viewplus/#/global_api?id=mixin-)，为什么，因为每个应用的ui风格是不一样的，所以，插件给你预留了钩子，你自己往里面填就行了，至于这个js ui模块，里面的方法你可以随意定义。

到此我觉得应该把插件安装这个坑天上了，至于使用过程中，肯定还有其他的疑问，大家可以另外开issue，我们会尽量解答。
@kzylmlfg 
到此

**Comment by Jiiiiiin** [comment]
@lifetin 还有就是不是什么只有_大项目_，哈哈才可以使用，你看这里[一个微信签到“小程序”](https://github.com/Jiiiiiin/tuobacco_sign_spa)，这个小示例其实并不大，可以说很小很小，但是我一样使用了，而且也只用了http模块，其实只要配置熟悉了，用起来很溜，没什么项目不可用使用，至少目前我这样认为

**Comment by lifetin** [comment]
感谢作者的耐心讲究. 
都回复这么多,让我无言以对呀.感情又想让我再踩一些坑.哈哈.
我个人认为吧, 从精简方面和体积来讲,能尽可能用原生ES5和ES6的方来实现,比喻你用lodas目的是什么,类型检测或是其它方法的精简?  这些类型检测,ES5+ES6里面的各方自带的方法,基本上可以满足了业务需求. 编译后也会进行babell转换.
然后有没有想过typeScript, 如果是为了程序的健壮,可以用这个来写,这样类型方面,其本上不用担心了.
还有关于你说的this的绑定问题, ES6中的promise,完全都没有this可言,大家也都过来了, bind和call,及副本_this,还有=>函数 ,应该满足99.9%的需求了. 
然后作为一个使用者来讲.项目要小,上线效率要快.然后还有一些其它的都要考虑.  如果新手来用,或是本身时间不够,然后又对这些配置及webpack,lodash,后编译,这些都不懂怎么办? 说的就是我. 哈哈. 因为我只会用vue cli去引用,编译什么的,为了考虑别的东西,我还要研究不少东西,可能还要踩不少坑. 这样来使用这个可能会适得其反. 因为还不如果自己去按自己项目需求来写自己的方法来满足要求.
我觉得吧.  这个模块,还有很多可优化的空间,精简是第一,去掉第三方的引用,也较重要. 后编译这个目前没有接触到.如果你觉得这个模块将来会比较大, 或是比较繁锁,你现在这样使用也没关系, 如果你觉得一定要任何人,一上来就能用, 不需要安装这,安装那的. 简单就安装上了,并使用了上, 那么也可以考虑暂时不用这个,   因为不是每个人都会配置,使用者也估计没有你懂的多.
再来说说vue cli这个, vue我们都是一键安装,什么都不用配置,npm一下子就能启动看到页面和编写代码了, 你这个模块没有他的复杂吧?  如果vue也是这样的,估计也没有多少人一下子就能上手和使用的了. 
还有用的vuex vue-route 这些, 我不需要怎么配置,npm一下子就能开始写了. 所以简单非常重要. 
个人见解,说的不对,还望作者理解.

**Comment by Jiiiiiin** [comment]
@lifetin 嗯 你说的有道理，因为这个插件是一个团队内部研习过来的，故为了快速实现，所以lodash还是被保留，后期可以计划使用typescript重写，但是又要马儿跑又要马儿不吃草是不可能的，也就是说，如果想要灵活开启和关闭模块，后编译是目前我觉得最靠谱的方案，当然不管是理解webpack周边配置还是理解插件模块配置都需要一个过程，这也是做这种插件不像做UI组件库那样能风风火火。
也谢谢你的建议，无论用不用都是一种交流 呵呵
周末我还是会考虑做一个模块toggle配置，这样就灵活一些，至少眼不见为净，比如如果只想使用某一个模块，整个插件就只会混合该模块的api到$vp。

🤝
